name: Build docker image
on:
  workflow_dispatch:
  push:
    branches:
      - build
jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build docker image
          run: tools/docker/build.sh

        - name: Upload image
          uses: ishworkh/docker-image-artifact-upload@v1
          with:
            image: quickblog:latest
