name: Deploying to remote server
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - deploy
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Archive posts
        run: npm --prefix tools/archiver start

      - name: Build dist
        run: tools/prepare.sh

      - name: Deploy via sso
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          ARGS: "-rv --delete --chmod=750"
          SOURCE: "dist/"
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}


